language: cpp
compiler:
  - gcc
  - clang
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-0-dev zlib1g-dev
script:
  - make NPROCS=1
  - make install
  - make -C kyototycoon check
