language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - liblua5.1-0-dev
      - zlib1g-dev
      - liblzo2-dev

script:
  - make NPROCS=1
  - make PREFIX=$HOME/kyoto NPROCS=1 install
  - make -j1 -C kyototycoon check
