#!/bin/bash -e


# Create the service user for KT...
if ! grep -q kyoto /etc/group; then
    groupadd -r kyoto
fi

# Create the service user for KT...
if ! grep -q kyoto /etc/passwd; then
    useradd -r -M -d /var/lib/kyoto -g kyoto -s /bin/false kyoto
fi

chown kyoto:kyoto /var/lib/kyoto
chown kyoto:kyoto /var/log/kyoto

# Set startup runlevels only on first install...
if [ -z "$2" ]; then
    update-rc.d kyoto defaults
fi

/etc/init.d/kyoto start


# vim: set expandtab ts=4 sw=4:
