#!/bin/bash -e


pkill -TERM -U "kyoto" || true
sleep 2

if ps -ef | grep -q ^[k]yoto; then
    echo "Killing Kyoto Tycoon processes by force..."
    pkill -KILL -U "kyoto" || true
fi

rm -f /var/run/kyoto.pid


# vim: set expandtab ts=4 sw=4:
