.TH "KCDIRMGR" 1 "2012-05-24" "Man Page" "Kyoto Cabinet"

.SH NAME
kcdirmgr \- command line interface to manage the directory hash database

.SH DESCRIPTION
.PP
The command `\fBkcdirmgr\fR' is a utility for test and debugging of the directory hash database and its applications.  `\fIpath\fR' specifies the path of a database file.  `\fIkey\fR' specifies the key of a record.  `\fIvalue\fR' specifies the value of a record.  `\fIfile\fR' specifies the input/output file.
.PP
.RS
.br
\fBkcdirmgr create \fR[\fB\-otr\fR]\fB \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-tc\fR]\fB \fIpath\fB\fR
.RS
Creates a database file.
.RE
.br
\fBkcdirmgr inform \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-st\fR]\fB \fIpath\fB\fR
.RS
Prints status information.
.RE
.br
\fBkcdirmgr set \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-add\fR|\fB\-app\fR|\fB\-rep\fR|\fB\-inci\fR|\fB\-incd\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB \fIvalue\fB\fR
.RS
Stores a record.
.RE
.br
\fBkcdirmgr remove \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB\fR
.RS
Removes a record.
.RE
.br
\fBkcdirmgr get \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-rm\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-px\fR]\fB \fR[\fB\-pz\fR]\fB \fIpath\fB \fIkey\fB\fR
.RS
Prints the value of a record.
.RE
.br
\fBkcdirmgr list \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-max \fInum\fB\fR]\fB \fR[\fB\-rm\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-pv\fR]\fB \fR[\fB\-px\fR]\fB \fIpath\fB \fR[\fB\fIkey\fB\fR]\fB\fR
.RS
Prints keys of all records, separated by line feeds.
.RE
.br
\fBkcdirmgr clear \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB\fR
.RS
Removes all records of a database.
.RE
.br
\fBkcdirmgr import \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Imports records from a TSV file.
.RE
.br
\fBkcdirmgr copy \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fIfile\fB\fR
.RS
Copies the whole database.
.RE
.br
\fBkcdirmgr dump \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Dumps records into a snapshot file.
.RE
.br
\fBkcdirmgr load \fR[\fB\-otr\fR]\fB \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Loads records from a snapshot file.
.RE
.br
\fBkcdirmgr defrag \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB\fR
.RS
Performs defragmentation.
.RE
.br
\fBkcdirmgr setbulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fIkey\fB \fIvalue\fB ...\fR
.RS
Store records at once.
.RE
.br
\fBkcdirmgr removebulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB ...\fR
.RS
Remove records at once.
.RE
.br
\fBkcdirmgr getbulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-px\fR]\fB \fIpath\fB \fIkey\fB ...\fR
.RS
Retrieve records at once.
.RE
.br
\fBkcdirmgr check \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB\fR
.RS
Checks consistency.
.RE
.RE
.PP
Options feature the following.
.PP
.RS
\fB\-otr\fR : opens the database with the truncation option.
.br
\fB\-onl\fR : opens the database with the no locking option.
.br
\fB\-otl\fR : opens the database with the try locking option.
.br
\fB\-onr\fR : opens the database with the no auto repair option.
.br
\fB\-tc\fR : tunes the database with the compression option.
.br
\fB\-st\fR : prints miscellaneous information.
.br
\fB\-add\fR : performs adding operation.
.br
\fB\-app\fR : performs appending operation.
.br
\fB\-rep\fR : performs replacing operation.
.br
\fB\-inci\fR : performs integer increment operation.
.br
\fB\-incd\fR : performs real number increment operation.
.br
\fB\-sx\fR : the input data is evaluated as a hexadecimal data string.
.br
\fB\-rm\fR : removes the record.
.br
\fB\-px\fR : the output data is converted into a hexadecimal data string.
.br
\fB\-pz\fR : does not append line feed at the end of the output.
.br
\fB\-max \fInum\fR\fR : specifies the maximum number of shown records.
.br
\fB\-pv\fR : prints values of records also.
.br
.RE
.PP
This command returns 0 on success, another on failure.

.SH SEE ALSO
.PP
.BR kcdirtest (1)
