.TH "KCFORESTMGR" 1 "2012-05-24" "Man Page" "Kyoto Cabinet"

.SH NAME
kcforestmgr \- command line interface to manage the directory tree database

.SH DESCRIPTION
.PP
The command `\fBkcforestmgr\fR' is a utility for test and debugging of the file tree database and its applications.  `\fIpath\fR' specifies the path of a database file.  `\fIkey\fR' specifies the key of a record.  `\fIvalue\fR' specifies the value of a record.  `\fIfile\fR' specifies the input/output file.
.PP
.RS
.br
\fBkcforestmgr create \fR[\fB\-otr\fR]\fB \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-tc\fR]\fB \fR[\fB\-bnum \fInum\fB\fR]\fB \fR[\fB\-psiz \fInum\fB\fR]\fB \fR[\fB\-rcd\fR|\fB\-rcld\fR|\fB\-rcdd\fR]\fB \fIpath\fB\fR
.RS
Creates a database file.
.RE
.br
\fBkcforestmgr inform \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-st\fR]\fB \fIpath\fB\fR
.RS
Prints status information.
.RE
.br
\fBkcforestmgr set \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-add\fR|\fB\-app\fR|\fB\-rep\fR|\fB\-inci\fR|\fB\-incd\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB \fIvalue\fB\fR
.RS
Stores a record.
.RE
.br
\fBkcforestmgr remove \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB\fR
.RS
Removes a record.
.RE
.br
\fBkcforestmgr get \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-rm\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-px\fR]\fB \fR[\fB\-pz\fR]\fB \fIpath\fB \fIkey\fB\fR
.RS
Prints the value of a record.
.RE
.br
\fBkcforestmgr list \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-des\fR]\fB \fR[\fB\-max \fInum\fB\fR]\fB \fR[\fB\-rm\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-pv\fR]\fB \fR[\fB\-px\fR]\fB \fIpath\fB \fR[\fB\fIkey\fB\fR]\fB\fR
.RS
Prints keys of all records, separated by line feeds.
.RE
.br
\fBkcforestmgr clear \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB\fR
.RS
Removes all records of a database.
.RE
.br
\fBkcforestmgr import \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Imports records from a TSV file.
.RE
.br
\fBkcforestmgr copy \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fIfile\fB\fR
.RS
Copies the whole database.
.RE
.br
\fBkcforestmgr dump \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Dumps records into a snapshot file.
.RE
.br
\fBkcforestmgr load \fR[\fB\-otr\fR]\fB \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fR[\fB\fIfile\fB\fR]\fB\fR
.RS
Loads records from a snapshot file.
.RE
.br
\fBkcforestmgr setbulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB \fIkey\fB \fIvalue\fB ...\fR
.RS
Store records at once.
.RE
.br
\fBkcforestmgr removebulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fIpath\fB \fIkey\fB ...\fR
.RS
Remove records at once.
.RE
.br
\fBkcforestmgr getbulk \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fR[\fB\-sx\fR]\fB \fR[\fB\-px\fR]\fB \fIpath\fB \fIkey\fB ...\fR
.RS
Retrieve records at once.
.RE
.br
\fBkcforestmgr check \fR[\fB\-onl\fR|\fB\-otl\fR|\fB\-onr\fR]\fB \fIpath\fB\fR
.RS
Checks consistency.
.RE
.RE
.PP
Options feature the following.
.PP
.RS
\fB\-otr\fR : opens the database with the truncation option.
.br
\fB\-onl\fR : opens the database with the no locking option.
.br
\fB\-otl\fR : opens the database with the try locking option.
.br
\fB\-onr\fR : opens the database with the no auto repair option.
.br
\fB\-tc\fR : tunes the database with the compression option.
.br
\fB\-bnum \fInum\fR\fR : specifies the number of buckets of the hash table.
.br
\fB\-psiz \fInum\fR\fR : specifies the size of each page.
.br
\fB\-rcd\fR : use the decimal comparator instead of the lexical one.
.br
\fB\-rcld\fR : use the lexical descending comparator instead of the ascending one.
.br
\fB\-rcdd\fR : use the decimal descending comparator instead of the lexical one.
.br
\fB\-st\fR : prints miscellaneous information.
.br
\fB\-add\fR : performs adding operation.
.br
\fB\-app\fR : performs appending operation.
.br
\fB\-rep\fR : performs replacing operation.
.br
\fB\-inci\fR : performs integer increment operation.
.br
\fB\-incd\fR : performs real number increment operation.
.br
\fB\-sx\fR : the input data is evaluated as a hexadecimal data string.
.br
\fB\-rm\fR : removes the record.
.br
\fB\-px\fR : the output data is converted into a hexadecimal data string.
.br
\fB\-pz\fR : does not append line feed at the end of the output.
.br
\fB\-des\fR : visits records in descending order.
.br
\fB\-max \fInum\fR\fR : specifies the maximum number of shown records.
.br
\fB\-pv\fR : prints values of records also.
.br
.RE
.PP
This command returns 0 on success, another on failure.

.SH SEE ALSO
.PP
.BR kcforesttest (1)
