.TH "KCPROTOTEST" 1 "2012-05-24" "Man Page" "Kyoto Cabinet"

.SH NAME
kcprototest \- command line interface to test the prototype database

.SH DESCRIPTION
.PP
The command `\fBkcprototest\fR' is a utility for facility test and performance test of the prototype database.  This command is used in the following format.  `\fIrnum\fR' specifies the number of iterations.
.PP
.RS
.br
\fBkcprototest order \fR[\fB\-tree\fR]\fB \fR[\fB\-th \fInum\fB\fR]\fB \fR[\fB\-rnd\fR]\fB \fR[\fB\-etc\fR]\fB \fR[\fB\-tran\fR]\fB \fIrnum\fB\fR
.RS
Performs in\-order tests.
.RE
.br
\fBkcprototest queue \fR[\fB\-tree\fR]\fB \fR[\fB\-th \fInum\fB\fR]\fB \fR[\fB\-it \fInum\fB\fR]\fB \fR[\fB\-rnd\fR]\fB \fIrnum\fB\fR
.RS
Performs queuing operations.
.RE
.br
\fBkcprototest wicked \fR[\fB\-tree\fR]\fB \fR[\fB\-th \fInum\fB\fR]\fB \fR[\fB\-it \fInum\fB\fR]\fB \fIrnum\fB\fR
.RS
Performs mixed operations selected at random.
.RE
.br
\fBkcprototest tran \fR[\fB\-tree\fR]\fB \fR[\fB\-th \fInum\fB\fR]\fB \fR[\fB\-it \fInum\fB\fR]\fB \fIrnum\fB\fR
.RS
Performs test of transaction.
.RE
.RE
.PP
Options feature the following.
.PP
.RS
\fB\-tree\fR : test the prototype tree database instead of the prototype hash database.
.br
\fB\-th \fInum\fR\fR : specifies the number of worker threads.
.br
\fB\-rnd\fR : performs random test.
.br
\fB\-etc\fR : performs miscellaneous operations.
.br
\fB\-tran\fR : performs transaction.
.br
\fB\-it \fInum\fR\fR : specifies the number of repetition.
.br
.RE
.PP
This command returns 0 on success, another on failure.
